baseURL: 'http://felipesilfer.github.io/'
title: Felipe Ferreira
paginate: 5
theme: lisrael
copyright: built by [**felipesilfer**](https://github.com/felipesilfer/), Brazil &copy; {year}

disqusShortname: felipesilfer-github-io



menu:
    main:
        - name: Contato
          url: /contact/
          weight: 30
        - name: Artigos
          url: /articles/
          weight: 20
#        - name: Projetos
#          url: /projects/
#          weight: 15

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Felipe Ferreira


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Olá, eu sou o Felipe 👋
        description: |

          Sou servidor público na UFF e estudante de ciência de dados. 
        
        imageUrl: "/images/profile.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Não clique!
              url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    mainSections:
      - articles

    socialIcons:
        - name: buymeacoffee
          url: "https://ko-fi.com/felipesilfer"
        - name: github
          url: "https://github.com/felipesilfer"
        - name: twitter
          url: "https://twitter.com/felipesilfer"
        - name: linkedin
          url: "https://www.linkedin.com/in/felipesilfer/"


      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

